### ISSUE TITLE
Okta Authentication - Undefined

### ISSUE THREAD

**Issue by ramyakandasamy7** [ramyakandasamy7/cmpe272CerealKillers#2]
When I tried logging in, I received the following message: "Welcome undefined undefined!" although it allows me to SSO into slack.

<img width="1483" alt="Screen Shot 2019-12-01 at 9 54 13 AM" src="https://user-images.githubusercontent.com/36056493/69917947-d697c100-1420-11ea-97d9-7387756b0016.png">

**Comment by ramyakandasamy7** [comment]
<img width="1009" alt="Screen Shot 2019-12-01 at 9 53 31 AM" src="https://user-images.githubusercontent.com/36056493/69917955-f62ee980-1420-11ea-8a23-3476984230d9.png">

<img width="544" alt="Screen Shot 2019-12-01 at 9 57 31 AM" src="https://user-images.githubusercontent.com/36056493/69917963-1068c780-1421-11ea-8c80-e93e748558b3.png">

**Comment by jedvillan** [comment]
I didn't know I was getting info from the cookie that only exists if you check the "Remember Me" checkbox when logging in. Changed it to get email from token. Everything should be working now.
