### ISSUE TITLE
Time Off - Working Days Incorrect

### ISSUE THREAD

**Issue by ramyakandasamy7** [ramyakandasamy7/cmpe272CerealKillers#3]
Javascript/node.js does its month calculations from 0-11 and the UI seems to be taking it as 1-12 so I suspect that is the issue. 

For example, 01/03-01/06 should return 16 hours, not 32 hours but I believe its because the code is attributing the "01" in January to February.

<img width="1078" alt="Screen Shot 2019-12-01 at 10 09 46 AM" src="https://user-images.githubusercontent.com/36056493/69918100-c5e84a80-1422-11ea-909b-b0a27b739d33.png">

**Comment by jedvillan** [comment]
Fixed by subtracting number of weekends to total days.

**Comment by ramyakandasamy7** [comment]
awesome, thank you Jed!
